apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app
  namespace: dev
spec:
  replicas: 2 # On lance 2 conteneurs pour la haute disponibilité
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
      - name: wil42
        image: wil42/playground:v2 # L'image Docker officielle
        ports:
        - containerPort: 8888
